import { Component } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable, tap } from 'rxjs';
import { AuthserviceService } from '../services/authservice.service';

@Component({
    selector: 'app-statistics-view',
    templateUrl: './statistics-view.component.html',
    styleUrls: ['./statistics-view.component.css'],
})
export class StatisticsViewComponent {
    constructor(
        private http: HttpClient,
        private authService: AuthserviceService
    ) {}

    groupby(xs: any, key: any) {
        return xs.reduce(function (rv: any, x: any) {
            (rv[x[key]] = rv[x[key]] || []).push(x);
            return rv;
        }, {});
    }
    //console.log(groupBy(['one', 'two', 'three'], 'length'));
    // => {"3": ["one", "two"], "5": ["three"]}

    allergens = [
        'GLUTEN',
        'EGGS',
        'MILK',
        'PEANUTS',
        'TREE_NUTS',
        'CELERY',
        'MUSTARD',
        'SESAME',
        'FISH',
        'CRUSTACEANS',
        'MOLLUSCS',
        'SOYA',
        'SULPHITES',
        'LUPIN',
        'MEAT',
    ];

    getTooltip(key: string) {
        let returnValue;

        switch (key) {
            case 'GLUTEN':
                returnValue = 'Glutén allergia';
                break;
            case 'PEANUTS':
                returnValue = 'Mogyoróallergia';
                break;
            case 'TREE_NUTS':
                returnValue = 'Diófélék allergia';
                break;
            case 'CELERY':
                returnValue = 'Zeller allergia';
                break;
            case 'MUSTARD':
                returnValue = 'Mustár allergia';
                break;
            case 'EGGS':
                returnValue = 'Tojás allergia';
                break;
            case 'MILK':
                returnValue = 'Tej allergia';
                break;
            case 'SESAME':
                returnValue = 'Szezámmag allergia';
                break;
            case 'FISH':
                returnValue = 'Hal allergia/Vegetárináus';
                break;
            case 'CRUSTACEANS':
                returnValue = 'Rákféle allergia/Vegetáriánus';
                break;
            case 'MOLLUSCS':
                returnValue = 'Tengergyümölcsei allergia';
                break;
            case 'SOYA':
                returnValue = 'Szója allergia';
                break;
            case 'SULPHITES':
                returnValue = 'Szulfát allergia';
                break;
            case 'LUPIN':
                returnValue = 'Lupin allergia';
                break;
            case 'MEAT':
                returnValue = 'Hús allergia/Vegetáriánus';
                break;
        }

        return returnValue;
    }

    getRandomInt(max: number) {
        return Math.floor(Math.random() * max);
    }

    menusTable = [
        {
            date: '2023-12-02',
            statistics: {
                glutenfree: 4,
                diaryfree: 2,
                vegan: 6,
            },
        },
        {
            date: '2023-12-03',
            statistics: {
                glutenfree: 3,
                diaryfree: 2,
                vegan: 5,
            },
        },
        {
            date: '2023-12-04',
            statistics: {
                glutenfree: 3,
                diaryfree: 2,
                vegan: 5,
            },
        },
        {
            date: '2023-12-05',
            statistics: {
                glutenfree: 3,
                diaryfree: 4,
                vegan: 5,
            },
        },
        {
            date: '2023-12-06',
            statistics: {
                glutenfree: 13,
                diaryfree: 4,
                vegan: 6,
            },
        },
    ];

    menusOrdered = [
        {
            id: 1,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Tojásmentes menü',
            date: '2023-12-02',
            occasion: 'FORENOON_FOOD',
            cost: 2310,
            foods: ['Lasagne'],
            allergens: [],
        },
        {
            id: 2,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halmentes menü',
            date: '2023-12-02',
            occasion: 'LUNCH',
            cost: 2610,
            foods: ['Sültcsirke', 'Rántotttojás', 'Káposzta'],
            allergens: ['FISH'],
        },
        {
            id: 3,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Paleo menü',
            date: '2023-12-02',
            occasion: 'AFTERNOON_FOOD',
            cost: 2220,
            foods: ['Lasagne', 'Tojásleves', 'Pacal'],
            allergens: ['MOLLUSCS', 'SULPHITES'],
        },
        {
            id: 4,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halal menü',
            date: '2023-12-04',
            occasion: 'FORENOON_FOOD',
            cost: 1790,
            foods: [
                'Rántotttojás',
                'Hamburger',
                'Káposztásbabfőzelék',
                'Zöldségleves',
            ],
            allergens: [
                'MILK',
                'MUSTARD',
                'FISH',
                'SESAME',
                'EGGS',
                'MOLLUSCS',
                'MEAT',
            ],
        },
        {
            id: 5,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Kóser menü',
            date: '2023-12-04',
            occasion: 'LUNCH',
            cost: 2780,
            foods: ['Halászlé', 'Káposztásbab'],
            allergens: ['MILK', 'EGGS'],
        },
        {
            id: 6,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Gluténmentes menü',
            date: '2023-12-07',
            occasion: 'FORENOON_FOOD',
            cost: 2270,
            foods: ['Halászlé', 'Spagetti Bolognese'],
            allergens: ['SESAME', 'SULPHITES', 'SOYA', 'MEAT'],
        },
        {
            id: 7,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Gluténmentes menü',
            date: '2023-12-07',
            occasion: 'LUNCH',
            cost: 2450,
            foods: ['Rántottkarfiol', 'Rizs', 'Sültcsirke', 'Sültkrumpli'],
            allergens: [],
        },
        {
            id: 8,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halal menü',
            date: '2023-12-07',
            occasion: 'AFTERNOON_FOOD',
            cost: 550,
            foods: ['Sültkrumpli'],
            allergens: [],
        },
        {
            id: 9,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Laktózmentes menü',
            date: '2023-12-08',
            occasion: 'FORENOON_FOOD',
            cost: 2000,
            foods: [
                'Káposztásbab',
                'Gulyásleves',
                'Káposztaleves',
                'Rántottbrokkoli',
            ],
            allergens: [],
        },
        {
            id: 10,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2023-12-09',
            occasion: 'LUNCH',
            cost: 2920,
            foods: ['Rántotttészta', 'Káposzta', 'Hotdog'],
            allergens: ['CELERY', 'MILK', 'LUPIN'],
        },
        {
            id: 11,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Paleo menü',
            date: '2023-12-09',
            occasion: 'AFTERNOON_FOOD',
            cost: 2770,
            foods: ['Tészta', 'Káposzta', 'Puding', 'Rántottkrumpli'],
            allergens: ['TREE_NUTS', 'GLUTEN', 'MOLLUSCS', 'MEAT'],
        },
        {
            id: 12,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2023-12-12',
            occasion: 'FORENOON_FOOD',
            cost: 930,
            foods: ['Káposztásbabfőzelék', 'Spagetti Carbonara'],
            allergens: [],
        },
        {
            id: 13,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2023-12-12',
            occasion: 'LUNCH',
            cost: 1790,
            foods: ['Kenyér', 'Hamburger', 'Lasagne', 'Sültkrumpli'],
            allergens: [],
        },
        {
            id: 14,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Kóser menü',
            date: '2023-12-12',
            occasion: 'AFTERNOON_FOOD',
            cost: 2010,
            foods: ['Spagetti Carbonara'],
            allergens: ['SULPHITES'],
        },
        {
            id: 15,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Diabetikus menü',
            date: '2023-12-13',
            occasion: 'LUNCH',
            cost: 2760,
            foods: [
                'Rántottkrumpli',
                'Spagetti Carbonara',
                'Káposztásbabfőzelék',
                'Krumplileves',
            ],
            allergens: [],
        },
        {
            id: 16,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Tojásmentes menü',
            date: '2023-12-17',
            occasion: 'FORENOON_FOOD',
            cost: 2450,
            foods: ['Sajt', 'Rántotttojás', 'Lasagne', 'Sültkrumpli'],
            allergens: ['GLUTEN'],
        },
        {
            id: 17,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegetáriánus menü',
            date: '2023-12-17',
            occasion: 'LUNCH',
            cost: 2300,
            foods: ['Gombaleves'],
            allergens: ['MUSTARD', 'CRUSTACEANS'],
        },
        {
            id: 18,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halmentes menü',
            date: '2023-12-17',
            occasion: 'AFTERNOON_FOOD',
            cost: 2720,
            foods: ['Rántottsajt', 'Kolbász', 'Puding', 'Gulyásleves'],
            allergens: ['FISH', 'SESAME', 'CRUSTACEANS', 'GLUTEN', 'MOLLUSCS'],
        },
        {
            id: 19,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Paleo menü',
            date: '2023-12-18',
            occasion: 'LUNCH',
            cost: 2270,
            foods: ['Gombaleves', 'Káposztásbabfőzelék', 'Halászlé'],
            allergens: ['SULPHITES'],
        },
        {
            id: 20,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Laktózmentes menü',
            date: '2023-12-18',
            occasion: 'AFTERNOON_FOOD',
            cost: 1810,
            foods: ['Spagetti Carbonara', 'Palócleves'],
            allergens: ['MILK'],
        },
        {
            id: 21,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Diabetikus menü',
            date: '2023-12-20',
            occasion: 'FORENOON_FOOD',
            cost: 2770,
            foods: ['Lasagne', 'Káposztásleves'],
            allergens: ['CRUSTACEANS', 'SESAME'],
        },
        {
            id: 22,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegán menü',
            date: '2023-12-22',
            occasion: 'LUNCH',
            cost: 1730,
            foods: ['Zöldségleves', 'Spagetti Bolognese', 'Sajt'],
            allergens: ['CRUSTACEANS', 'LUPIN'],
        },
        {
            id: 23,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Kóser menü',
            date: '2023-12-24',
            occasion: 'FORENOON_FOOD',
            cost: 1240,
            foods: ['Tészta', 'Rizs', 'Húsleves', 'Káposztásbab'],
            allergens: ['CRUSTACEANS', 'MOLLUSCS', 'FISH'],
        },
        {
            id: 24,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Gluténmentes menü',
            date: '2023-12-24',
            occasion: 'LUNCH',
            cost: 2380,
            foods: ['Rántottsajt', 'Rántottgomba', 'Rántottkolbász'],
            allergens: ['MOLLUSCS'],
        },
        {
            id: 25,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegán menü',
            date: '2023-12-24',
            occasion: 'AFTERNOON_FOOD',
            cost: 960,
            foods: [
                'Káposztaleves',
                'Rántottkarfiol',
                'Pizza',
                'Rántotttészta',
            ],
            allergens: ['MUSTARD', 'MOLLUSCS', 'EGGS'],
        },
        {
            id: 26,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2023-12-25',
            occasion: 'LUNCH',
            cost: 2590,
            foods: ['Káposztásbab', 'Rántottsajt'],
            allergens: [],
        },
        {
            id: 27,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Laktózmentes menü',
            date: '2023-12-28',
            occasion: 'FORENOON_FOOD',
            cost: 1090,
            foods: ['Spagetti Carbonara', 'Csirke', 'Torta'],
            allergens: [],
        },
        {
            id: 28,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halal menü',
            date: '2023-12-28',
            occasion: 'LUNCH',
            cost: 890,
            foods: ['Rizs', 'Rántottbrokkoli'],
            allergens: ['EGGS'],
        },
        {
            id: 29,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Tojásmentes menü',
            date: '2023-12-29',
            occasion: 'FORENOON_FOOD',
            cost: 2310,
            foods: ['Káposztásbab'],
            allergens: [],
        },
        {
            id: 30,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2023-12-29',
            occasion: 'LUNCH',
            cost: 2190,
            foods: ['Tészta', 'Krumpli', 'Rántotttojás'],
            allergens: [],
        },
        {
            id: 31,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Kóser menü',
            date: '2023-12-29',
            occasion: 'AFTERNOON_FOOD',
            cost: 1110,
            foods: ['Sajt'],
            allergens: [],
        },
        {
            id: 32,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegetáriánus menü',
            date: '2023-12-31',
            occasion: 'FORENOON_FOOD',
            cost: 2880,
            foods: ['Rántottgomba', 'Bableves'],
            allergens: ['PEANUTS', 'MOLLUSCS'],
        },
        {
            id: 33,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Laktózmentes menü',
            date: '2023-12-31',
            occasion: 'AFTERNOON_FOOD',
            cost: 1120,
            foods: ['Hotdog', 'Káposztásbab'],
            allergens: ['SESAME'],
        },
        {
            id: 34,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Laktózmentes menü',
            date: '2024-01-05',
            occasion: 'AFTERNOON_FOOD',
            cost: 2220,
            foods: [
                'Sültcsirke',
                'Rántottkrumpli',
                'Rántottkolbász',
                'Halászlé',
            ],
            allergens: ['CELERY', 'TREE_NUTS'],
        },
        {
            id: 35,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Paleo menü',
            date: '2024-01-07',
            occasion: 'FORENOON_FOOD',
            cost: 1830,
            foods: [
                'Bableves',
                'Krumplileves',
                'Spagetti Bolognese',
                'Káposzta',
            ],
            allergens: ['CRUSTACEANS'],
        },
        {
            id: 36,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Diabetikus menü',
            date: '2024-01-07',
            occasion: 'LUNCH',
            cost: 2730,
            foods: ['Hamburger', 'Rántottgomba', 'Spagetti Bolognese'],
            allergens: ['MEAT', 'SOYA'],
        },
        {
            id: 37,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halal menü',
            date: '2024-01-07',
            occasion: 'AFTERNOON_FOOD',
            cost: 510,
            foods: ['Rántotttojás', 'Káposzta', 'Gulyásleves'],
            allergens: ['MUSTARD', 'SESAME', 'FISH'],
        },
        {
            id: 38,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegetáriánus menü',
            date: '2024-01-10',
            occasion: 'LUNCH',
            cost: 2150,
            foods: ['Rántottcsirke'],
            allergens: [],
        },
        {
            id: 39,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Kóser menü',
            date: '2024-01-11',
            occasion: 'FORENOON_FOOD',
            cost: 2640,
            foods: ['Puding', 'Zöldségleves'],
            allergens: [],
        },
        {
            id: 40,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegán menü',
            date: '2024-01-11',
            occasion: 'LUNCH',
            cost: 2900,
            foods: ['Pizza', 'Hamburger', 'Káposztásbab'],
            allergens: ['MUSTARD', 'FISH'],
        },
        {
            id: 41,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halmentes menü',
            date: '2024-01-12',
            occasion: 'LUNCH',
            cost: 2420,
            foods: ['Hamburger'],
            allergens: ['MILK', 'CRUSTACEANS'],
        },
        {
            id: 42,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2024-01-12',
            occasion: 'AFTERNOON_FOOD',
            cost: 1980,
            foods: ['Rántottkolbász'],
            allergens: ['MUSTARD', 'CRUSTACEANS'],
        },
        {
            id: 43,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halal menü',
            date: '2024-01-13',
            occasion: 'AFTERNOON_FOOD',
            cost: 1270,
            foods: ['Palócleves', 'Rántotttojás', 'Gulyásleves'],
            allergens: [],
        },
        {
            id: 44,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegán menü',
            date: '2024-01-14',
            occasion: 'LUNCH',
            cost: 1250,
            foods: ['Kolbász'],
            allergens: [],
        },
        {
            id: 45,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2024-01-17',
            occasion: 'FORENOON_FOOD',
            cost: 2870,
            foods: [
                'Krumplileves',
                'Rántottbrokkoli',
                'Spagetti Carbonara',
                'Torta',
            ],
            allergens: ['CRUSTACEANS', 'LUPIN', 'EGGS'],
        },
        {
            id: 46,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halal menü',
            date: '2024-01-17',
            occasion: 'LUNCH',
            cost: 1030,
            foods: [
                'Káposzta',
                'Spagetti Carbonara',
                'Káposztásleves',
                'Krumplileves',
            ],
            allergens: ['SULPHITES'],
        },
        {
            id: 47,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Paleo menü',
            date: '2024-01-18',
            occasion: 'LUNCH',
            cost: 2730,
            foods: ['Tojásleves', 'Torta', 'Spagetti Carbonara'],
            allergens: ['MUSTARD'],
        },
        {
            id: 48,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halmentes menü',
            date: '2024-01-19',
            occasion: 'LUNCH',
            cost: 2730,
            foods: [
                'Spagetti Bolognese',
                'Rántotttészta',
                'Rántottbrokkoli',
                'Hotdog',
            ],
            allergens: ['LUPIN', 'SOYA', 'FISH'],
        },
        {
            id: 49,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Laktózmentes menü',
            date: '2024-01-21',
            occasion: 'FORENOON_FOOD',
            cost: 2020,
            foods: ['Gombaleves'],
            allergens: ['FISH', 'SESAME'],
        },
        {
            id: 50,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Paleo menü',
            date: '2024-01-22',
            occasion: 'FORENOON_FOOD',
            cost: 890,
            foods: ['Húsleves'],
            allergens: ['CELERY', 'MOLLUSCS'],
        },
        {
            id: 51,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2024-01-22',
            occasion: 'LUNCH',
            cost: 2500,
            foods: ['Rántottkarfiol', 'Halászlé', 'Puding', 'Hotdog'],
            allergens: ['CRUSTACEANS', 'SOYA', 'GLUTEN'],
        },
        {
            id: 52,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Tojásmentes menü',
            date: '2024-01-22',
            occasion: 'AFTERNOON_FOOD',
            cost: 770,
            foods: ['Rántottkrumpli', 'Rántotttojás', 'Csirke', 'Torta'],
            allergens: ['PEANUTS', 'MOLLUSCS', 'EGGS'],
        },
        {
            id: 53,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2024-01-23',
            occasion: 'FORENOON_FOOD',
            cost: 1670,
            foods: ['Húsleves', 'Krumpli', 'Rántottkaralábé', 'Rántottcsirke'],
            allergens: [],
        },
        {
            id: 54,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegán menü',
            date: '2024-01-24',
            occasion: 'FORENOON_FOOD',
            cost: 1810,
            foods: ['Puding', 'Rántottkaralábé', 'Sajt', 'Káposztásbab'],
            allergens: ['MEAT'],
        },
        {
            id: 55,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Paleo menü',
            date: '2024-01-24',
            occasion: 'AFTERNOON_FOOD',
            cost: 2190,
            foods: ['Kolbász', 'Húsleves'],
            allergens: ['MEAT', 'SULPHITES', 'SOYA', 'CRUSTACEANS', 'EGGS'],
        },
        {
            id: 56,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2024-01-25',
            occasion: 'LUNCH',
            cost: 1820,
            foods: ['Halászlé', 'Rántottbrokkoli'],
            allergens: [],
        },
        {
            id: 57,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2024-01-25',
            occasion: 'AFTERNOON_FOOD',
            cost: 1720,
            foods: ['Káposzta', 'Sültkrumpli', 'Tészta'],
            allergens: [],
        },
        {
            id: 58,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegetáriánus menü',
            date: '2024-01-26',
            occasion: 'FORENOON_FOOD',
            cost: 2660,
            foods: [
                'Rántottkolbász',
                'Pacal',
                'Káposztaleves',
                'Rántottkrumpli',
            ],
            allergens: ['SOYA', 'SESAME', 'MEAT'],
        },
        {
            id: 59,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Kóser menü',
            date: '2024-01-26',
            occasion: 'LUNCH',
            cost: 1930,
            foods: ['Kenyér', 'Káposztaleves'],
            allergens: ['SOYA'],
        },
        {
            id: 60,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Halmentes menü',
            date: '2024-01-27',
            occasion: 'LUNCH',
            cost: 580,
            foods: [
                'Káposztásbabfőzelék',
                'Hotdog',
                'Spagetti Carbonara',
                'Rántottkaralábé',
            ],
            allergens: ['MILK', 'SESAME'],
        },
        {
            id: 61,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Paleo menü',
            date: '2024-01-27',
            occasion: 'AFTERNOON_FOOD',
            cost: 780,
            foods: ['Káposztásleves', 'Rántottgomba'],
            allergens: [],
        },
        {
            id: 62,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Gluténmentes menü',
            date: '2024-01-28',
            occasion: 'AFTERNOON_FOOD',
            cost: 2340,
            foods: ['Lasagne'],
            allergens: [],
        },
        {
            id: 63,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2024-02-05',
            occasion: 'FORENOON_FOOD',
            cost: 870,
            foods: ['Húsleves', 'Rántottcsirke', 'Káposztásbabfőzelék'],
            allergens: [],
        },
        {
            id: 64,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Szójamentes menü',
            date: '2024-02-05',
            occasion: 'LUNCH',
            cost: 1160,
            foods: [
                'Rántottzöldség',
                'Gulyásleves',
                'Puding',
                'Káposztásbabfőzelék',
            ],
            allergens: [],
        },
        {
            id: 65,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Laktózmentes menü',
            date: '2024-02-06',
            occasion: 'LUNCH',
            cost: 2170,
            foods: ['Zöldségleves', 'Halászlé'],
            allergens: ['CELERY'],
        },
        {
            id: 66,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Diabetikus menü',
            date: '2024-02-08',
            occasion: 'FORENOON_FOOD',
            cost: 580,
            foods: ['Hotdog'],
            allergens: [],
        },
        {
            id: 67,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Diabetikus menü',
            date: '2024-02-08',
            occasion: 'LUNCH',
            cost: 510,
            foods: ['Káposztásbabfőzelék', 'Bableves', 'Rántottzöldség'],
            allergens: ['MILK'],
        },
        {
            id: 68,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Vegán menü',
            date: '2024-02-09',
            occasion: 'LUNCH',
            cost: 2640,
            foods: ['Rántottgomba', 'Káposztásbab'],
            allergens: ['CELERY', 'SOYA'],
        },
        {
            id: 69,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Gluténmentes menü',
            date: '2024-02-11',
            occasion: 'LUNCH',
            cost: 1530,
            foods: ['Rántottsajt', 'Rántotttojás', 'Lasagne'],
            allergens: ['MUSTARD'],
        },
        {
            id: 70,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Gluténmentes menü',
            date: '2024-02-11',
            occasion: 'AFTERNOON_FOOD',
            cost: 2200,
            foods: ['Rántottsajt', 'Rántottkrumpli'],
            allergens: ['PEANUTS', 'LUPIN', 'GLUTEN'],
        },
        {
            id: 71,
            organization: { id: 1, name: 'Eötvös Középiskola' },
            name: 'Tojásmentes menü',
            date: '2024-02-13',
            occasion: 'LUNCH',
            cost: 630,
            foods: ['Káposztásleves'],
            allergens: ['CRUSTACEANS', 'SULPHITES'],
        },
    ];

    menusGroupedByDate = this.groupby(this.menusOrdered, 'date');
}
