name: 'Build and test: backend'

on:
  push:
    paths: ['sceat-backend/**']
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and test
      working-directory: ./sceat-backend
      run: mvn clean package
    - name: Determine project properties
      id: properties
      working-directory: ./sceat-backend
      run: |
        echo "name=$(mvn help:evaluate -Dexpression="project.build.finalName" -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload built JAR
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.properties.outputs.name }}-${{ steps.properties.outputs.hash }}.jar
        path: ./sceat-backend/target/${{ steps.properties.outputs.name }}.jar
        if-no-files-found: error
