name: 'Build and test: backend'

on:
  push:
    paths: ['sceat-backend/**']
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and test
      working-directory: ./sceat-backend
      run: mvn clean package
    - name: Determine project properties
      id: properties
      run: |
        echo ::set-output name=name::$(mvn help:evaluate -Dexpression="project.build.finalName" -q -DforceStdout)
        echo ::set-output name=hash::$(git rev-parse --short HEAD)
    - name: Upload built JAR
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.properties.outputs.name }}-${{ steps.properties.outputs.hash }}.jar
        path: target/${{ steps.properties.outputs.name }}.jar
